### ISSUE TITLE
Graph line does not show up

### ISSUE THREAD

**Issue by alanjones2** [mljar/bloxs#1]
The bloxs examples work fine on Colab but when I transfer the same code to my local machine the charts do not show up. The block appears with the text in it but the graph is missing. I've tried with Jupyter Notebook, Jupyter Lab and VSCode all with the same result. I'm using Anaconda Python 3.9.7

![Screenshot 2022-04-05 171301](https://user-images.githubusercontent.com/6489432/161786670-ed6d404c-0b71-4d36-bad4-7b2a7e5b219e.png)
.

**Comment by pplonski** [comment]
Do you have internet connection on machine running Jupyter Notebook? The chart library is served with CDN.

**Comment by alanjones2** [comment]
Yes, I do but you are right, it is a problem fetching charts.js

![image](https://user-images.githubusercontent.com/6489432/161933765-94aa3912-721c-4127-9a87-d4564bdeafaa.png)

This seems to be suggesting that it succeeds and then fails.

If I point my browser directly at charts.min.js it loads, so I don't really know what is going on here. I'll take another look later.

**Comment by alanjones2** [comment]
I've looked at it in Chrome now and it seems that charts.min.js **is** being loaded but it seems maybe it's slow

**Comment by virtadpt** [comment]
I'm seeing this as well - latest version installed into Miniconda.

**Comment by pplonski** [comment]
@virtadpt thanks for confirming.

The solution might be to inject the `chart.min.js` file in `<script>` tag directly to `ipynb` file. I need to check.

**Comment by khuyentran1401** [comment]
I also can't see the line chart

**Comment by pplonski** [comment]
@khuyentran1401 thanks for reporting. Are you running Jupyter Notebook locally?

I think it should be changed to inject the charts lib instead cdn link.

**Comment by khuyentran1401** [comment]
Yes. How can I change that?

**Comment by pplonski** [comment]
@khuyentran1401 the code needs to be updated, here is the code that inject `Chart.js` CDN 

https://github.com/mljar/bloxs/blob/d809b8ec45df3d0ddab73cf212893070c73d5ee1/bloxs/bloxs.py#L139-L147

and the chart.js file is already in the repo. I will try to fix that right now, please give me some time.

**Comment by khuyentran1401** [comment]
That sounds great. Thank you!

**Comment by pplonski** [comment]
I've created a StackOverflow question for this issue https://stackoverflow.com/questions/73124130/use-chart-js-in-jupyter-notebook-throws-uncaught-referenceerror-chart-is-not-d - I hope I will get som tips how to solve this issue. Sorry for problems

**Comment by pplonski** [comment]
It should be working now :) I've released the version `1.0.2`.

![Peek 2022-07-27 16-32](https://user-images.githubusercontent.com/6959032/181274511-4415895e-5035-4bad-b05a-2d3ef4670e00.gif)
