### ISSUE TITLE
Fill color not affected when using hex color definition

### ISSUE THREAD

**Issue by alanjones2** [mljar/bloxs#2]
If you specify a color in hex, e.g.

` B("Rain",year,points=rain, color="#FF6384")`

This only changes the line color in a line graph and has no visible effect on the lighter fill color.
With a bar graph there is no visible effect.

Could there be a `fill-color` parameter, too? That way we could match the colors appropriately.

**Comment by pplonski** [comment]
@alanjones2 I've added two parameters:
- `border_color` to set border color in the graph,
- `fill_color` to set fill color.

If they are set then `color` parameter is not used. The changes are in the version `1.0.2`.

### Example
![image](https://user-images.githubusercontent.com/6959032/181272559-8b15af43-3580-48d1-ba13-e4533bb4ad99.png)
